### ISSUE TITLE
expose new responseType option in IRequestOptions

### ISSUE THREAD

**Issue by sfabijanski** [Esri/arcgis-rest-js#373]
I'm working with Node 8.6.0 in a linux environment. I was trying to request an image export from an image server when I ran into an error: "error: TypeError: response.blob is not a function." When the format is set to *image* rather than resolve with the image buffer, the request throws an error.

I've traced the error down to the format setting. When the parameters are set and format is *image* the promise should resolve and the image buffer should be returned, but it does not, and throws an error in **request.ts**. Based on the structure of that file, and the switch statement on *params.f* I'm guessing that the 'zip' format will also fail.

Investigating a bit further I found #bitinn/node-fetch/issues/78  which references response.blob being browser only. 

I put together a quick test:
``` javascript
require("isomorphic-fetch");
require("isomorphic-form-data");

const { request } = require("@esri/arcgis-rest-request");
const imageServiceURL = 'https://geodata.md.gov/imap/rest/services/Imagery/MD_SixInchImagery/ImageServer';

// if f='json' this will work in Node
// when f='image' request fails with 'response.blob is not a function' error
const params = {
  bbox: '-8529110,4764085,-8528610,4764085',
  bboxSR: '102100',
  size: '400,400',
  imageSR: '102100',
  format: 'png8',
  pixelType: 'U8',
  noDataInterpretation: 'esriNoDataMatchAny',
  interpolation: '+RSP_BilinearInterpolation',
  f: 'image'
};

request(imageServiceURL + '/exportimage', { httpMethod: 'POST', params })
.then( result => {
  console.log({result});
})
.catch( error => { console.log({error})});

```

**Comment by jgravois** [comment]
thanks for taking the time to write up what you found. for the time being you might consider using node-fetch@^2.0.0

```js
const fetch = require("node-fetch");
request(imageServiceURL + '/exportimage', { 
  httpMethod: 'POST', 
  params,
  fetch
})
```

related: https://github.com/matthew-andrews/isomorphic-fetch/pull/157

**Comment by tomwayson** [comment]
alternatively you could try https://github.com/developit/unfetch/tree/master/packages/isomorphic-unfetch

**Comment by jgravois** [comment]
see https://github.com/Esri/arcgis-rest-js/pull/374#issuecomment-435133941

https://developer.mozilla.org/en-US/docs/Web/API/Response#Methods

**Comment by sfabijanski** [comment]
I've researched this issue much more deeply since my initial request and *finally* understand the differences between a stream and a buffer. Please follow @patrickarlt 's [advice](https://github.com/Esri/arcgis-rest-js/pull/374#issuecomment-434732939) suggesting the inclusion of both **buffer** and **stream** for response types. Since streams are also supported in the browser, see [Stream API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API), they would be the most efficient means of processing large responses. 

Both arrayBuffer and buffer force: 1) completion of the response before processing, and 2) the entire contents of the response to be stored in memory. Streams allow acting on the data before the response completes and store only portions of the data in memory when response is large. Per @jgravois's original [approach](https://github.com/Esri/arcgis-rest-js/commit/95a35ce793dd98d719b46d371cce7e98783885a6), returning the *body* from fetch's response object  is indeed the preferred default to support Node as it provides access to the stream.

**Comment by tomwayson** [comment]
Re-opening this issue in light of the re-kindled conversation in https://github.com/Esri/arcgis-rest-js/pull/374#issuecomment-462553066

**Comment by jgravois** [comment]
closed via #457. thx @tannerjt! 🚀

**Comment by thw0rted** [comment]
Anybody following this might be have insight on my question in #462 , i.e. do we need a new issue to have all the methods that think they return a JSON collection, but can now also return a `Response`, updated to account for this?
